// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Feliz.MaterialUI.Pickers")>]
[<assembly: AssemblyProductAttribute("Feliz.MaterialUI.Pickers")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings written in the Feliz-style for material-ui-pickers")>]
[<assembly: AssemblyVersionAttribute("0.2.1")>]
[<assembly: AssemblyFileVersionAttribute("0.2.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Feliz.MaterialUI.Pickers.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Feliz.MaterialUI.Pickers"
    let [<Literal>] AssemblyProduct = "Feliz.MaterialUI.Pickers"
    let [<Literal>] AssemblyDescription = "Fable bindings written in the Feliz-style for material-ui-pickers"
    let [<Literal>] AssemblyVersion = "0.2.1"
    let [<Literal>] AssemblyFileVersion = "0.2.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Feliz.MaterialUI.Pickers.Tests"
